/** macOS LaunchAgent — plist generation + launchctl lifecycle controls.
 *
 * References OpenClaw's launchd.ts design: KeepAlive for crash recovery,
 * RunAtLoad for boot autostart, ThrottleInterval for crash-loop backoff,
 * and a separate 0600 env file for secrets.
 */

import { mkdir, writeFile, unlink, chmod } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { SERVICE_DIR, TEXT_LOG_PATH as LOG_PATH } from "../paths.js";
import type { DaemonConfig, DaemonManager } from "./types.js";

const execFileAsync = promisify(execFile);

const LAUNCH_AGENT_LABEL = "ai.myos.gateway";
const PLIST_DIR = join(homedir(), "Library", "LaunchAgents");
const PLIST_PATH = join(PLIST_DIR, `${LAUNCH_AGENT_LABEL}.plist`);
const ENV_FILE = join(SERVICE_DIR, "gateway.env");
const ENV_WRAPPER = join(SERVICE_DIR, "wrapper.sh");
// stderr goes to the same log — /dev/null would make daemon-side config
// errors (e.g. missing env var at startup) completely invisible
const STDERR_PATH = LOG_PATH;

const EXIT_TIMEOUT_SECONDS = 20;
const THROTTLE_INTERVAL_SECONDS = 10;

// ─── Plist generation ────────────────────────────────────────────

function plistEscape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function buildPlist(config: DaemonConfig): string {
  const argsXml = config.programArguments
    .map((arg) => `\n      <string>${plistEscape(arg)}</string>`)
    .join("");

  const workingDirXml = config.workingDirectory
    ? `\n    <key>WorkingDirectory</key>\n    <string>${plistEscape(config.workingDirectory)}</string>`
    : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>${plistEscape(LAUNCH_AGENT_LABEL)}</string>
    <key>Comment</key>
    <string>${plistEscape(config.description)}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>ExitTimeOut</key>
    <integer>${EXIT_TIMEOUT_SECONDS}</integer>
    <key>ThrottleInterval</key>
    <integer>${THROTTLE_INTERVAL_SECONDS}</integer>
    <key>ProcessType</key>
    <string>Interactive</string>
    <key>ProgramArguments</key>
    <array>${argsXml}
    </array>${workingDirXml}
    <key>StandardOutPath</key>
    <string>${plistEscape(config.logPath)}</string>
    <key>StandardErrorPath</key>
    <string>${plistEscape(STDERR_PATH)}</string>
  </dict>
</plist>
`;
}

// ─── Environment file ────────────────────────────────────────────

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function buildEnvFile(environment: Record<string, string>): string {
  const lines = Object.entries(environment)
    .filter(([, v]) => v?.trim())
    .map(([k, v]) => `export ${k}=${shellSingleQuote(v.trim())}`);
  return [
    "# Generated by MyOS. Do not edit while the service is installed.",
    ...lines,
    "",
  ].join("\n");
}

function buildEnvWrapper(): string {
  return `#!/bin/sh
set -eu
env_file="$1"
shift
if [ -f "$env_file" ]; then
  . "$env_file"
fi
exec "$@"
`;
}

// ─── launchctl helpers ───────────────────────────────────────────

function guiDomain(): string {
  return typeof process.getuid === "function"
    ? `gui/${process.getuid()}`
    : "gui/501";
}

function serviceTarget(): string {
  return `${guiDomain()}/${LAUNCH_AGENT_LABEL}`;
}

async function launchctl(args: string[]): Promise<{ stdout: string; stderr: string; code: number }> {
  try {
    const { stdout, stderr } = await execFileAsync("launchctl", args, {
      timeout: 15_000,
    });
    return { stdout, stderr, code: 0 };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; code?: number };
    return {
      stdout: e.stdout ?? "",
      stderr: e.stderr ?? "",
      code: e.code ?? 1,
    };
  }
}

function isNotLoaded(result: { stdout: string; stderr: string }): boolean {
  const detail = (result.stderr || result.stdout).toLowerCase();
  return (
    detail.includes("no such process") ||
    detail.includes("could not find service") ||
    detail.includes("not found")
  );
}

// ─── Manager ─────────────────────────────────────────────────────

export class LaunchdManager implements DaemonManager {
  readonly backend = "launchd" as const;
  private config: DaemonConfig;

  constructor(config: DaemonConfig) {
    this.config = config;
  }

  /** Write the 0600 secrets env file from the current environment/config.
   *  Called on install AND start/restart so a rotated key takes effect
   *  without requiring a re-install. */
  private async writeEnvFile(): Promise<boolean> {
    const envEntries = this.config.environment ?? {};
    if (Object.keys(envEntries).length === 0) return false;
    const content = buildEnvFile(envEntries);
    await mkdir(SERVICE_DIR, { recursive: true, mode: 0o700 });
    await writeFile(ENV_FILE, content, { mode: 0o600 });
    await chmod(ENV_FILE, 0o600).catch(() => {});
    return true;
  }

  async install(): Promise<void> {
    // Write env file (0600) + wrapper script (0700)
    await mkdir(SERVICE_DIR, { recursive: true, mode: 0o700 });

    const envEntries = this.config.environment ?? {};
    await this.writeEnvFile();

    await writeFile(ENV_WRAPPER, buildEnvWrapper(), { mode: 0o700 });
    await chmod(ENV_WRAPPER, 0o700).catch(() => {});

    // Build program arguments — prepend env wrapper if we have env vars
    const programArguments =
      Object.keys(envEntries).length > 0
        ? ["/bin/sh", ENV_WRAPPER, ENV_FILE, ...this.config.programArguments]
        : this.config.programArguments;

    // Write plist
    await mkdir(PLIST_DIR, { recursive: true, mode: 0o755 });
    const plist = buildPlist({ ...this.config, programArguments });
    await writeFile(PLIST_PATH, plist, { mode: 0o644 });
    await chmod(PLIST_PATH, 0o644).catch(() => {});

    // Ensure log directory exists
    await mkdir(dirname(this.config.logPath), { recursive: true });

    // Bootout if already loaded, then bootstrap
    await launchctl(["bootout", guiDomain(), PLIST_PATH]);
    const target = serviceTarget();
    await launchctl(["enable", target]);
    const boot = await launchctl(["bootstrap", guiDomain(), PLIST_PATH]);
    if (boot.code !== 0 && !isNotLoaded(boot)) {
      // Already loaded is OK
      const detail = (boot.stderr || boot.stdout).toLowerCase();
      if (!detail.includes("already exists")) {
        throw new Error(`launchctl bootstrap failed: ${boot.stderr || boot.stdout}`);
      }
    }

    process.stdout.write(`[myos] LaunchAgent installed: ${PLIST_PATH}\n`);
    process.stdout.write(`[myos] Logs: ${this.config.logPath}\n`);
  }

  async uninstall(): Promise<void> {
    const target = serviceTarget();
    await launchctl(["bootout", target]);
    await launchctl(["unload", PLIST_PATH]);

    // Move plist to Trash (like OpenClaw does)
    const trashPath = join(homedir(), ".Trash", `${LAUNCH_AGENT_LABEL}.plist`);
    try {
      const { rename } = await import("node:fs/promises");
      await mkdir(join(homedir(), ".Trash"), { recursive: true });
      await rename(PLIST_PATH, trashPath);
      process.stdout.write(`[myos] LaunchAgent moved to Trash: ${trashPath}\n`);
    } catch {
      // Plist may not exist
    }

    // Clean env files
    await unlink(ENV_FILE).catch(() => {});
    await unlink(ENV_WRAPPER).catch(() => {});

    process.stdout.write(`[myos] LaunchAgent uninstalled\n`);
  }

  async start(): Promise<void> {
    // Refresh secrets so a rotated key takes effect
    await this.writeEnvFile().catch(() => {});
    const target = serviceTarget();
    await launchctl(["enable", target]);
    const result = await launchctl(["kickstart", target]);
    if (result.code !== 0 && isNotLoaded(result)) {
      // Service not bootstrapped — load plist first
      const boot = await launchctl(["bootstrap", guiDomain(), PLIST_PATH]);
      if (boot.code !== 0) {
        throw new Error(`launchctl bootstrap failed: ${boot.stderr || boot.stdout}`);
      }
    } else if (result.code !== 0) {
      throw new Error(`launchctl kickstart failed: ${result.stderr || result.stdout}`);
    }
    process.stdout.write(`[myos] LaunchAgent started: ${target}\n`);
  }

  async stop(): Promise<void> {
    const target = serviceTarget();
    const result = await launchctl(["bootout", target]);
    if (result.code !== 0 && !isNotLoaded(result)) {
      throw new Error(`launchctl bootout failed: ${result.stderr || result.stdout}`);
    }
    process.stdout.write(`[myos] LaunchAgent stopped: ${target}\n`);
  }

  async restart(): Promise<void> {
    // Refresh secrets so a rotated key takes effect
    await this.writeEnvFile().catch(() => {});
    const target = serviceTarget();
    // kickstart -k restarts the service (kills + restarts)
    const result = await launchctl(["kickstart", "-k", target]);
    if (result.code !== 0 && isNotLoaded(result)) {
      // Service not bootstrapped — bootstrap instead
      const boot = await launchctl(["bootstrap", guiDomain(), PLIST_PATH]);
      if (boot.code !== 0) {
        throw new Error(`launchctl bootstrap failed: ${boot.stderr || boot.stdout}`);
      }
    } else if (result.code !== 0) {
      throw new Error(`launchctl kickstart -k failed: ${result.stderr || result.stdout}`);
    }
    process.stdout.write(`[myos] LaunchAgent restarted: ${target}\n`);
  }

  async status(): Promise<void> {
    const target = serviceTarget();
    const result = await launchctl(["print", target]);
    if (result.code !== 0) {
      const plistExists = await this.plistExists();
      if (plistExists) {
        process.stdout.write(`[myos] LaunchAgent installed but not loaded\n`);
        process.stdout.write(`[myos] Plist: ${PLIST_PATH}\n`);
      } else {
        process.stdout.write(`[myos] LaunchAgent not installed\n`);
      }
      return;
    }

    const output = result.stdout;
    const stateMatch = output.match(/state\s*=\s*(\S+)/);
    const pidMatch = output.match(/pid\s*=\s*(\d+)/);
    const state = stateMatch?.[1] ?? "unknown";
    const pid = pidMatch?.[1];

    if (state === "running" || pid) {
      process.stdout.write(`[myos] LaunchAgent running (PID ${pid ?? "?"})\n`);
    } else {
      process.stdout.write(`[myos] LaunchAgent stopped (state: ${state})\n`);
    }
    process.stdout.write(`[myos] Plist: ${PLIST_PATH}\n`);
    process.stdout.write(`[myos] Logs: ${this.config.logPath}\n`);
  }

  async isInstalled(): Promise<boolean> {
    return this.plistExists();
  }

  async isRunning(): Promise<boolean> {
    const target = serviceTarget();
    const result = await launchctl(["print", target]);
    if (result.code !== 0) return false;
    const output = result.stdout.toLowerCase();
    return output.includes("state = running") || /pid\s*=\s*\d+/.test(output);
  }

  private async plistExists(): Promise<boolean> {
    try {
      const { access } = await import("node:fs/promises");
      await access(PLIST_PATH);
      return true;
    } catch {
      return false;
    }
  }
}

export const LAUNCH_AGENT_PATHS = {
  plistPath: PLIST_PATH,
  envFile: ENV_FILE,
  envWrapper: ENV_WRAPPER,
  logPath: LOG_PATH,
  label: LAUNCH_AGENT_LABEL,
};
